# Generated by Django 2.0.8 on 2019-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(default='media/me.jpg', upload_to=''),
        ),
    ]
