# Generated by Django 2.0.8 on 2019-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_profile_selfie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(default='me.jpg', upload_to=''),
        ),
    ]
