# Generated by Django 2.0.8 on 2019-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_auto_20190319_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
