# Generated by Django 2.0.8 on 2019-03-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0007_auto_20190319_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(blank=True, default='media/me.jpg', null=True, upload_to=''),
        ),
    ]
