# Generated by Django 2.0.8 on 2019-03-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0008_auto_20190320_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to=''),
        ),
    ]
