# Generated by Django 2.0.8 on 2019-03-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0013_auto_20190328_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='graduated_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selfie',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to=''),
        ),
    ]
