# Generated by Django 2.0.8 on 2019-04-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0014_auto_20190328_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='awards',
            field=models.TextField(blank=True),
        ),
    ]
