# Generated by Django 2.2 on 2020-04-04 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrument', '0001_initial'),
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applying',
            name='announce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='announce.Announce'),
        ),
        migrations.AddField(
            model_name='applying',
            name='applier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applying',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='announce',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announces', to='instrument.Instrument'),
        ),
        migrations.AddField(
            model_name='announce',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announces', to=settings.AUTH_USER_MODEL),
        ),
    ]
