# Generated by Django 2.0.8 on 2019-03-25 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='applier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
