# Generated by Django 2.0.8 on 2019-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announce', '0002_applying_applier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='deadline',
            field=models.DateField(),
        ),
    ]
