# Generated by Django 2.2 on 2020-04-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('intro', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('selfie', models.ImageField(blank=True, default='me.jpg', null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('intro', models.TextField()),
                ('experience', models.TextField(blank=True)),
                ('selfie', models.ImageField(blank=True, default='me.jpg', null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
