# Generated by Django 2.2 on 2020-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200404_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='resumetemplate',
            name='intro',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(default='테스트학력', verbose_name='학력'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.TextField(default='테스트 제목', verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='education',
            field=models.TextField(default='테스트학력1', verbose_name='학력'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='title',
            field=models.TextField(default='테스트학력2', verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, verbose_name='경력'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='selfie',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='', verbose_name='사진'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='experience',
            field=models.TextField(blank=True, verbose_name='경력'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='selfie',
            field=models.ImageField(blank=True, default='me.jpg', null=True, upload_to='', verbose_name='사진'),
        ),
    ]
