# Generated by Django 2.2 on 2020-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200614_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='경력'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='experience',
            field=models.TextField(verbose_name='경력'),
        ),
    ]
